### ISSUE TITLE
Frontend design feedback

### ISSUE THREAD

**Issue by spaghetus** [chromezoneeths/ethsbell-rewrite#18]
### Style Changes
- [x] ~~#20~~
- [x] #19
### Layout Changes
- [x] #31
- [x] #32
- [x] #22
- [x] #39
- [x] #40
### Schedule
- [x] #21
- [x] #30
- [x] #29
### New/Changed Functionality
- [x] #23
  - [x] #24
- [x] #25
- [x] #26
### Issues
- [x] #27
- [x] #28
### To Be Discussed
- [x] ~~Merge timeline with schedule~~
- [x] Move extension options page to popup

**Comment by asportnoy** [comment]
All issues completed, closing this.
