### ISSUE TITLE
---- Confetti ----

### ISSUE THREAD

**Issue by Navnedia** [chromezoneeths/ethsbell-rewrite#42]
It would be a cool/fun touch if you could add confetti to the website and Extension (if possible). The confetti could go off after each period, or maybe just at the end of the day. I think It would also be nice if there's a window that you can see the confetti in after the end of the event, that way you don't have to actively be on the page at that exact moment to see it. **For Example**, say I go and look at the site for the first time 30 minutes after the end of school, it would be cool if the animation would still play on the "School's out!" screen within a certain window after the end (with a short delay to allow the page to load). And maybe the animation only plays the first time you load the page after the end event, that way they can't just keep refreshing to see it again, meaning it stays special and they have to wait till tomorrow to see it again. 

**Here's an example of what I'm thinking, and it also includes some example code:** [Confetti/Code Example](https://codemyui.com/falling-confetti/)

I like the colors in the Example, but you could also make it configurable with your theming stuff if you want. 

That's my fun suggestion, take it or leave it, lol. I think it would be really unique.

**Comment by Navnedia** [comment]
**Here is another cool Example:** [https://codepen.io/linrock/pen/Amdhr/](https://www.youtube.com/watch?v=iik25wqIuFo)

**Comment by asportnoy** [comment]
This seems stale, so I'm closing it for now. If anyone wants to take this on, feel free.
