### ISSUE TITLE
Swipe Refresh Issue

### ISSUE THREAD

**Issue by Navnedia** [chromezoneeths/ethsbell-rewrite#43]
Using the timeline page side-scrolling menu on a chrome book will instead do the back and forward hand gestures for chrome resulting in the page going back to the previous page constantly. Also, Consider ways you can make it clearer that the timeline is scrollable.

**Comment by spaghetus** [comment]
Fixed in 8f216a8dd6b00dfad5f1bf0e4022beed4c318bfa
