### ISSUE TITLE
Config Features 

### ISSUE THREAD

**Issue by Navnedia** [chromezoneeths/ethsbell-rewrite#44]
**I have five ideas that would really enhance this page:**

- [x] #48

- [x] #49

- [x] #50
- [x] #51
- [x] #52

**Comment by spaghetus** [comment]
1. Yes, I can do that.
2. I can try.
3. Oh boy that'll be a pain but I can do it
4. This is a consequence of the browser's anchor tag behavior, which assumes URLs without schemes to be relative to the current page. I can automatically add an URL scheme if the URL doesn't have one.
5. Default view could be switched to using https://developer.mozilla.org/en-US/docs/Web/API/Document/referrer to detect whether the user has come from one of our pages; if they haven't, we could redirect them to their configured default. It would also be a good idea to add a query string to bypass this behavior when linking to the homepage.

**Comment by asportnoy** [comment]
These are all implemented so I am closing this issue.
