### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by spaghetus** [chromezoneeths/ethsbell-rewrite#46]
- [ ] Add the domain to the [Google Search Console](https://search.google.com/search-console)
    - [ ] Optionally other search consoles too
- [x] Add robots.txt and sitemap.xml
- [x] Add meta tags with site info

**Comment by asportnoy** [comment]
- [ ] Add the domain to the [Google Search Console](https://search.google.com/search-console)
    - [ ] Optionally other search consoles too
- [ ] Add robots.txt and sitemap.xml
- [ ] Add meta tags with site info

**Comment by asportnoy** [comment]
Blocked for adding to search console (needs mr chan)

**Comment by asportnoy** [comment]
SEO seems pretty good, we are currently the top result for "ETHSBell". We should still get it added to the search console though.

**Comment by chanatown** [comment]
Added to search console. Let me know if you need permissions, reports, etc.
