### ISSUE TITLE
New config page breaks when user doesn't configure everything

### ISSUE THREAD

**Issue by spaghetus** [chromezoneeths/ethsbell-rewrite#58]
The new configuration page breaks if the user sets only their default page and nothing else.

**Comment by spaghetus** [comment]
[Video](https://imgur.com/a/W7EUphz)

**Comment by asportnoy** [comment]
Ah ok I'll get that fixed.

**Comment by spaghetus** [comment]
I'm adding emergency advisory support now since you were so adamant we didn't need it :roll_eyes:

**Comment by asportnoy** [comment]
Fixed in b03c6247ab7a8cf8a734269e32a928c717b76f36 and 2eb83a7029bee6c9e4a26b56f422631bc88320ff
