### ISSUE TITLE
Make schedules separate from rest of code

### ISSUE THREAD

**Issue by asportnoy** [chromezoneeths/ethsbell-rewrite#66]
Benefits:
- Can edit schedules without needing to rebuild or do anything with git
- Can have multiple instances with different schedules without needing to fork the repository or have uncommitted changes (eg for day school)
- Easier to manage for above reasons
- We'll fix #33 to work with this new system

**Comment by spaghetus** [comment]
The schedules are already configurable. The ones included in the repository are only the default.

* When deploying with Docker, a new schedule directory can be mounted using a Docker volume, the same way we did for our deployment.
* When deploying without Docker, you shouldn't be running it from the same directory as the source code anyway. You should compile it, then copy everything into another directory to run, just like we do in the Docker build process.

I agree that we need to fix the schedule editor, though.
