### ISSUE TITLE
Custom Title Duplication

### ISSUE THREAD

**Issue by Navnedia** [chromezoneeths/ethsbell-rewrite#69]
**Bug Description:**
After clicking around the schedule view a few times custom names become really long with duplicate words. The long custom names then carry over to other pages on the website till you refresh your webpage at which point the long names are reset.

**To Reproduce:**
Steps to reproduce the behavior (note, there may be other ways to trigger this but this is what I found)

1. Go to the config page.
2. Add some custom block names.
3. Make sure the box labeled "Include default period name when displaying" is checked (bug only seems to appear when this box is checked).
4. Save settings.
5. Go to the Schedule page.
6. Scroll down and click between two or more of the day types in the table or on the same day multiple times and the custom name part starts to duplicate.
7. You can also then go to the timeline page. At first it may seem normal, but if you start to scroll on the timeline the names with becoming those same long names. 

**Expected behavior:**
I think the expected behavior should be clear, the name should not be getting longer and duplicating. 

**Screenshots**
See attached files for screenshots and videos

https://user-images.githubusercontent.com/87249556/130874157-7c3db3bf-12e3-44ba-a894-0b7ce9409d1f.mp4

![Example](https://user-images.githubusercontent.com/87249556/130874175-be14556a-18a0-487c-ad74-a318b703302c.PNG)

![Settings](https://user-images.githubusercontent.com/87249556/130874176-fd697169-85a4-429a-a66b-3d180dc13d68.PNG)

**Comment by asportnoy** [comment]
Released in v1.6.8, confirmed resolved by @mswider.
