### ISSUE TITLE
Incorrect time zone behavior

### ISSUE THREAD

**Issue by spaghetus** [chromezoneeths/ethsbell-rewrite#77]
**Describe the bug**
When using the service either using Firefox's `privacy.resistFingerprinting` flag\* or from a different time zone than the server, incorrect times and durations are displayed.

**To Reproduce**
1. Open the website on Firefox with the `privacy.resistFingerprinting` flag set, or using any browser from a non-Chicago time zone

**Expected behavior**
Correct period end times and remaining durations

**Screenshots**
https://media.discordapp.net/attachments/621521865491480586/889920903369072760/unknown.png
https://media.discordapp.net/attachments/621521865491480586/889920958880706581/unknown.png
https://media.discordapp.net/attachments/621521865491480586/889921487874703360/unknown.png
https://media.discordapp.net/attachments/621521865491480586/889922352815681587/unknown.png
https://media.discordapp.net/attachments/621521865491480586/889922423800098827/unknown.png

**Server Version**

```json
["1.6.9","1a2c06133120917bcf92bdb15d9f0c0fd12f996e","chromezoneeths/ethsbell-rewrite"]
```

**OS/Browser Info**
https://www.whatsmybrowser.org/b/ZF7E4
(OS report is incorrect due to fingerprinting protection)

\* Returns UTC time regardless of the user's time zone to reduce fingerprinting surface

**Comment by asportnoy** [comment]
But even in that case, we would want it to be displayed in the local time zone, which your workaround would not solve

**Comment by spaghetus** [comment]
I'm not sure if you understood my reply, offsetting the schedule using the difference between remote and local time would do exactly that

**Comment by asportnoy** [comment]
I think I see what you're saying. It looks like it's displaying the times an hour ahead instead of an hour behind and vice versa.
